version: '1'

services: # Nests our containers under the “services” field

  video-streaming:
    image: film-streaming # Sets the name of the image
    build: 
    # Sets parameters required for building the image
      context: ./film-streaming
      dockerfile: Dockerfile
    container_name: film-streaming
    ports:
     - "4000:80"
    environment:
      - PORT=80
    restart: "no" # If the microservice crashes, don’t automatically restart it.
